### PR TITLE
Updated to lux 2.0.0-1

### PR DESCRIPTION
**Pull request by ifandelse**

### CODE REVIEW

**Comment by JohnDMathis** [comment]
@ifandelse Pulled down and ran tests. 29 passing! But, I don't seem to have write access, so I can't merge...

**Comment by dcneiner** [comment]
@ifandelse There is still a peer dependency on babel 5.x. Do we want to update that to 6.x?

**Comment by ifandelse** [comment]
Yes I'll have to do it when I get in

**Comment by rniemeyer** [comment]
Will merge this, just waiting on the peer dep change.

**Pull request merged**
